### ISSUE TITLE
Run time error on android device: Abort signal 6

### ISSUE THREAD

**Issue by PratikGajera** [nemirst/ntl-android#1]
Dear nemirst,

Nice ntl library source code given for android!
I builded ntl library source code for android using NDK. When I used it in my application, then getting runtime error is abort signal 6 from libc.so. And I had many research on this error and finally could be known, issue was coming from ntl library in error is "length too big in vector::SetLength" from WordVector.c source file. I am stucked over here, Kindly help me.

**Comment by nemirst** [comment]
Hello,
Please give as short as possible code examples, which causes crash. What kind of ABI are you using. Did you run build & tests successfully using this source tree?

**Comment by PratikGajera** [comment]
Thanks for your quick response!
I am building native library(.so) of Whitebox cryptography which I want to run on android platform and below following details:

i) I am using NDK version(android-ndk-r13b).
ii) I am using ABI: armeabi-v7a for android device.

Building native Whitebox Cryptography library is dependent on NTL library. Please find attached Whitebox cryptography source code link:

https://github.com/ph4r05/Whitebox-crypto-AES

**Comment by nemirst** [comment]
You probably built NTL on different ABI (for example arm64-v8a), but run it on armeabi-v7a where size of long is lower. On what ABI NTL was built? If you say it's armeabi-v7a, then please copy also NTL build & test logs. Please copy here NTL_BITS_PER_LONG value in mach_desc.h, which is generated during NTL compilation.

**Comment by PratikGajera** [comment]
Error resloved!
Thank you so much nemirst.

But another error "inv: non-invertible matrix" is coming from my application. I unable to understand that what is going wrong.

**Comment by nemirst** [comment]
Can't help you with that. Probably you are using Whitebox-crypto-AES incorrectly or modified it. I'm also using Whitebox-crypto-AES and run it without problems with my Android NTL library. You can trace out which method is being called and see what input is given and what output is produced. If there's mismatch then we can look at it.

**Comment by PratikGajera** [comment]
Dear nemirst,

Sorry, I am new in NDK. So I didn't know how can issue traced. Kindly help me. 

I am building whitebox cryptography library using given prebuilt libntl.a library. But, error is getting function undefinded reference.
Please find below error log.

/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(GF2X.o):function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >::sentry::~sentry(): error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(GF2X.o):function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >::flush(): error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(GF2X.o):function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >& std::__ndk1::__put_character_sequence<char, std::__ndk1::char_traits<char> >(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__ndk1::ios_base::getloc() const'
/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(GF2X.o):function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >& std::__ndk1::__put_character_sequence<char, std::__ndk1::char_traits<char> >(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__ndk1::locale::use_facet(std::__ndk1::locale::id&) const'
/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(GF2X.o):function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >& std::__ndk1::__put_character_sequence<char, std::__ndk1::char_traits<char> >(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__ndk1::locale::~locale()'
/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(GF2X.o):function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >& std::__ndk1::__put_character_sequence<char, std::__ndk1::char_traits<char> >(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__ndk1::ios_base::clear(unsigned int)'
/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(GF2X.o):function std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >& std::__ndk1::__put_character_sequence<char, std::__ndk1::char_traits<char> >(std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >&, char const*, unsigned int): error: undefined reference to 'std::__ndk1::ctype<char>::id'
/home/test/NDK/android-ndk-r13b/Whitebox_Native/jni/../samples/./prebuilt/armeabi-v7a/libntl.a(tools.o):function NTL::TerminalError(char const*): error: undefined reference to 'std::__ndk1::cerr'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/home/test/NDK/android-ndk-r13b/Whitebox_Native/obj/local/armeabi-v7a/WhiteboxCrypto] Error 1

**Comment by nemirst** [comment]
Prebuilt libraries were built using Android NDK 14 so you probably can't
compile them with your C++ code which uses Android NDK 13. But I think
error is related to NDK C++ library mismatch -  make sure you are using
same NDK C++ library everywhere.
For example, in Android NTL I use c++_static:
https://github.com/nemirst/ntl-android/blob/master/src/makefile#L358
See description of NDK C++ library types here:
https://developer.android.com/ndk/guides/cpp-support.html

2017-07-14 15:03 GMT+03:00 PratikGajera <notifications@github.com>:

**Comment by PratikGajera** [comment]
Thank you so much to Nemirst. Without your support, I coudn't build native library of Whitebox cryptography for android device.

**Comment by atunc** [comment]
hello @PratikGajera, i am trying to compile same project and i have similar errors from libntl.a. There is nothing changed when i used ndk 14 and compile ntl again. How did you compile could you help me please?
